/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_cachelib_CacheLibClient */

#ifndef _Included_site_ycsb_db_cachelib_CacheLibClient
#define _Included_site_ycsb_db_cachelib_CacheLibClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_cachelib_CacheLibClient
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_cachelib_CacheLibClient_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     site_ycsb_db_cachelib_CacheLibClient
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_cachelib_CacheLibClient_nativeCleanup
  (JNIEnv *, jobject);

/*
 * Class:     site_ycsb_db_cachelib_CacheLibClient
 * Method:    nativeInsert
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_site_ycsb_db_cachelib_CacheLibClient_nativeInsert
  (JNIEnv *, jobject, jstring, jstring, jbyteArray);

/*
 * Class:     site_ycsb_db_cachelib_CacheLibClient
 * Method:    nativeRead
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_ycsb_db_cachelib_CacheLibClient_nativeRead
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     site_ycsb_db_cachelib_CacheLibClient
 * Method:    nativeUpdate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_site_ycsb_db_cachelib_CacheLibClient_nativeUpdate
  (JNIEnv *, jobject, jstring, jstring, jbyteArray);

/*
 * Class:     site_ycsb_db_cachelib_CacheLibClient
 * Method:    nativeDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_site_ycsb_db_cachelib_CacheLibClient_nativeDelete
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
